== REP 1 - The Red Enhancement Process

[width="100%"]
|============================================
|REP:|1
|Title:|The Red Enhancement Process
|Author:|Peter W A Wood
|Status:|Permanent
|Date Created:|22-Apr-2018
|Date Last Actioned|22-Apr-2018
|============================================

== Introduction
Although Red is still in the alpha phase of its bootstrap release and far from complete, there are a growing number of requests for additional features and functionality. This process has been put in place to guide people who are requesting additions or changes to Red how to get them properly considered and possibly accepted.

The requests being made vary widely in size. Some are quite small, some would require significant amounts of work. Similarly, some could be implemented in the bootstrap release, some could only be implemented once self-hosted Red has been released (i.e. Red 2.0).

This process was introduced before the Red Foundation was established and RED tokens were created. It will be updated to be based on tokenomics at a later date.  

== Red Design Decisions
Red is not designed by committee. Nenad makes all design decisions. Having said that Nenad has demonstrated that he does not make design decisions in isolation. He frequently consults people on design decisions and has clearly taken their views into account. 

== The Red Enhancement Proposal Process
There are five stages in the Red proposal process, namely:

* Stage 1 - Proposal Development
* Stage 2 - Indication of Community Support
* Stage 3 - Proposal Evaluation
* Stage 4 - Proposal Implementation
* Stage 5 - Proposal Implemented

=== Stage 1 - Proposal Development
Anyone requesting a change or audition to Red should prepare a draft proposal in AsciiDoc format. The file name of the proposal should be in the form `rep-<initials>-<yyyy-mm-dd>.adoc`. The proposal should follow the REP 2 which defines the proposal format. There should be a separate proposal for each change or addition requested. 

The proposal should include the following information:
==== Description
A clear, concise description of the change/addition to Red that is being requested.
==== Use Case
An example or examples of how the change/addition would be used if it was implemented.
==== Benefits
An extensive explanation of all the benefits to the Red project supported by the rationale behind each benefit.
==== Consequences
Every enhancement, no matter how beneficial, will have some consequences that will need to be addressed. These range from requiring changes to existing documentation through to breaking all previous code (and probably beyond).
==== Assistance
Details of any assistance the proposer(s) is willing to give to implement the change/addition. This could be in the form of code, written tests, documentation or a donation.

Once the proposal has been completed, a pull request should be made to commit it to this repository. 

=== Stage 2 - Indication of Community Support
One factor that will be taken into account in evaluating proposals will be the level of support that they have in the Red community. As the community is still quite small, though starting to grow quickly, to start with support of five people will be sufficient to indicate that the proposal is of interest to the community. They should indicate their support by submitting a comment on the pull request.

Once a proposal has the required level of support, it will be reviewed by the Red Team. If the proposal is considered correctly formatted, complete and reasonable, it will be allocated a REP number and move to Stage 3 of the process.

=== Stage 3 - Proposal Evaluation
Proposals will be evaluated and if accepted will be scheduled for implementation.

=== Stage 4 - Proposal Implementation
Proposals will be scheduled in a future Red release. Once scheduled they may be rescheduled according to the needs of the project.

=== Stage 5 - Proposal Implemented
The proposal has been implemented.
