== REP 3 - Red Documentation

[width="100%"]
|============================================
|REP:|3
|Title:|Red Documentation
|Author:|Peter W A Wood
|Status:|Draft
|Date Created:|1-Aug-2018
|Date Last Actioned|11-Sep-2018
|============================================

== Introduction
The Red Foundation develops and maintains four types of documents for Red.

=== Specifications
These are formal specifications of the Red language and its major dialects. The relevant syntax will be formally documented using Backus-Naur Form (BNF) notation. The semantics will be concisely described using a formal style. 

These documents are targeted at language implementors.

=== References
These are reference documents that provide detailed information on the content of Red and its major dialects. They provide minimal explanation on usage and few examples.

These documents are targeted at experienced programmers familiar with Red (or similar languages). The https://www.lua.org/manual/5.3/[Lua Reference Manual] and the https://docs.python.org/3/reference/index.html[Python Reference Manual] provide similar levels of detail. (Though both also incude elements of formal language specification in addition to their reference information.)

=== User Guides
These are fuller explanations of Red and its major dialects including more detailed examples.

These documents are targeted mainly to programmers new to Red. The http://www.rebol.com/docs/core23/rebolcore.html[Rebol/Core User Manual] and https://www.lua.org/pil/contents.html[Programming in Lua] provide similar levels of detail.

=== Tutorials
These are basic Red programming tutorials. 

They are aimed at people new to a programming domain or specific feature.  

== Red Documentation
The following documents will be published by the Red Foundation.

[cols="2,4*"]
|===

|
|Specification
|Reference
|User Guide
|Tutorial

|Red Language
|Not Yet Written
|Not Yet Writtenfootnote:[includes libRed API & RedBin]
|Not Provided
|Not Provided

|Red Compiler
|Not Provided
|Not Yet Written
|Not Provided
|Not Provided

|Red Runtimefootnote:[including interpreter]
|Not Provided
|Not Yet Written
|Not Provided
|Not Provided

|Red Console
|Not Provided
|Not Yet Written
|Not Provided
|Not Provided

|Red Core, Console & Toolchainfootnote:[The Red User Guide]
|Not Provided
|Not Provided
|Not Yet Writtenfootnote:[includes Parse]
|Not Yet Writtenfootnote:[excludes Parse]

|Red GUIfootnote:[includes View, VID and Draw]
|Not Yet Written
|Written
|Not Yet Written
|Not Yet Written

|Parse
|Not Yet Written
|Not Yet Written
|Not Provided
|Not Yet Written

|Red/System Language
|Writtenfootnote:[An updated BNF Grammar]
|Writtenfootnote:[The current specification]
|Not Provided
|Not Provided

|Red/C3
|Not Yet Written
|Not Yet Written
|Not Yet Written
|Not Yet Written

|===

